title: Just the Docs Template
description: A starter template for a Jekyll site using the Just the Docs theme!
remote_theme: pmarsceill/just-the-docs

url: https://SWOT-Confluence.github.io/just-the-docs

aux_links:
  Template Repository: https://github.com/SWOT-Confluence/just-the-docs

just_the_docs:
  navigation:
    - title: "Home"
      url: /
    - title: "Guides"
      children:
        - title: "Introduction"
          url: /guides/intro/
        - title: "Advanced Topics"
          url: /guides/advanced/
