title: Confluence Documentation
description: SWOT Confluence Documentation
theme: just-the-docs

url: https://SWOT-Confluence.github.io/just-the-docs

aux_links:
  Template Repository: https://github.com/SWOT-Confluence/just-the-docs

just_the_docs:
  navigation: # Define navigation menu
    - title: "Home"
      url: /
    - title: "guides"
      url: /guides
      children:
      - title: "Introduction"
        url: /guides/intro
      - title: "Advanced Topics"
        url: /guides/Running_on_HPC