title: Just the Docs Template
description: A starter template for a Jekyll site using the Just the Docs theme!
theme: just-the-docs

url: https://SWOT-Confluence.github.io/just-the-docs

aux_links:
  Template Repository: https://github.com/SWOT-Confluence/just-the-docs

just_the_docs:
  navigation: # Define navigation menu
    - title: "Home"
      url: /

    - title: "Introduction"
      url: /intro
    - title: "Advanced Topics"
      url: /advanced
