title: "My Documentation Site"
remote_theme: pmarsceill/just-the-docs # Points to the Just the Docs theme
search_enabled: true # Enable site search
aux_links: # Optional: Add links in the navigation bar
  "GitHub":
    - url: https://github.com/your-repo
    - icon: "fab fa-github"
  
# Navigation order (optional, you can also define this in the page's front matter)
just_the_docs:
  navigation:
    - title: "Home"
      url: /
    - title: "Guides"
      children:
        - title: "Introduction"
          url: /guides/intro/
        - title: "Advanced Topics"
          url: /guides/advanced/

# Optional: Site-wide defaults for Markdown processing
markdown:
  kramdown:
    input: GFM
    hard_wrap: false
